### ISSUE TITLE
Error when  'make LibCarla'

### ISSUE THREAD

**Issue by JoveIC** [carla-simulator/carla#875]
Hi,

I'm using Ubuntu 18.04.1 LTS.
And I got this list of errors shown below: (Full log attached.) 
[log.txt](https://github.com/carla-simulator/carla/files/2481649/log.txt)

BuildLibCarla.sh: Building LibCarla "Server" configuration.
[1/51] Building CXX object LibCarla/cm.../__/__/source/carla/client/Image.cpp.o
FAILED: LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o 
/usr/bin/clang++-5.0  -DBOOST_ERROR_CODE_HEADER_ONLY -I../../LibCarla/cmake/../source -I../boost-1.67.0-install/include -I../rpclib-2.2.1-libcxx-install/include -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wno-missing-braces -stdlib=libc++ -I/home/ic/UnrealEngine_4.19/carla/Build/llvm-5.0-install/include/c++/v1 -std=c++14 -pthread -fPIC -Werror -Wall -Wextra -Wno-missing-braces -stdlib=libc++ -I/home/ic/UnrealEngine_4.19/carla/Build/llvm-5.0-install/include/c++/v1   -O3 -DNDEBUG -MD -MT LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o -MF LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o.d -o LibCarla/cmake/server/CMakeFiles/carla_server.dir/__/__/source/carla/client/Image.cpp.o -c ../../LibCarla/source/carla/client/Image.cpp
In file included from ../../LibCarla/source/carla/client/Image.cpp:8:
In file included from ../../LibCarla/cmake/../source/carla/client/Image.h:9:
../../LibCarla/cmake/../source/carla/Buffer.h:204:42: error: no member named 'is_const_buffer_sequence' in namespace 'boost::asio'
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                            ~~~~~~~~~~~~~^
../../LibCarla/cmake/../source/carla/Buffer.h:204:67: error: 'T' does not refer to a value
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                                                                  ^
../../LibCarla/cmake/../source/carla/Buffer.h:203:24: note: declared here
    template <typename T>
                       ^
../../LibCarla/cmake/../source/carla/Buffer.h:204:71: error: member 'value' declared as a template
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                                                                      ^
../../LibCarla/cmake/../source/carla/Buffer.h:204:76: error: expected ';' at end of declaration list
    typename std::enable_if<boost::asio::is_const_buffer_sequence<T>::value>::type
                                                                           ^
                                                                           ;
../../LibCarla/cmake/../source/carla/Buffer.h:97:9: error: use of undeclared identifier 'ReuseThisBuffer'
        ReuseThisBuffer();
        ^
5 errors generated.

Thank you for your help.

**Comment by Manojbhat09** [comment]
I am facing the same issue @JoveIC. I think its an issue with the new update. What system are you building on? I am using Windows WSL ubuntu.

**Comment by Manojbhat09** [comment]
check these out:
https://github.com/carla-simulator/carla/issues/813
https://github.com/carla-simulator/carla/issues/864

**Comment by JoveIC** [comment]
@Manojbhat09  I'm doing a fresh install, and I'm using Ubuntu 18.04.1 LTS

**Comment by Manojbhat09** [comment]
Hey @JoveIC   i fixed it!
### SUCCESS

What i changed from setup.sh:
BOOST_BASENAME=boost-1.67.0

BOOST_INCLUDE=${PWD}/${BOOST_BASENAME}-install/include
BOOST_LIBPATH=${PWD}/${BOOST_BASENAME}-install/lib

if [[ -d "${BOOST_BASENAME}-install" ]] ; then
  log "${BOOST_BASENAME} already installed."
else

  rm -Rf ${BOOST_BASENAME}-source

  log "Retrieving boost."
  wget https://dl.bintray.com/boostorg/release/1.6.0/source/boost_1_67_0.tar.gz
  log "Extracting boost."
  tar -xzf boost_1_67_0.tar.gz
  rm boost_1_67_0.tar.gz
  mkdir -p ${BOOST_BASENAME}-install/include
  mv boost_1_67_0 ${BOOST_BASENAME}-source
  # rm -Rf boost_1_67_0

  pushd ${BOOST_BASENAME}-source >/dev/null

  BOOST_TOOLSET="clang-5.0"
  BOOST_CFLAGS="-fPIC -std=c++14 -DBOOST_ERROR_CODE_HEADER_ONLY"

  ./bootstrap.sh \
      --with-toolset=clang \
      --prefix=../boost-install \
      --with-libraries=python
  ./b2 clean
  ./b2 toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12 stage release
  ./b2 install toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12

  popd >/dev/null


to:
BOOST_BASENAME=boost-1.68.0

BOOST_INCLUDE=${PWD}/${BOOST_BASENAME}-install/include
BOOST_LIBPATH=${PWD}/${BOOST_BASENAME}-install/lib

if [[ -d "${BOOST_BASENAME}-install" ]] ; then
  log "${BOOST_BASENAME} already installed."
else

  rm -Rf ${BOOST_BASENAME}-source

  log "Retrieving boost."
  wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
  log "Extracting boost."
  tar -xzf boost_1_68_0.tar.gz
  rm boost_1_68_0.tar.gz
  mkdir -p ${BOOST_BASENAME}-install/include
  mv boost_1_68_0 ${BOOST_BASENAME}-source
  # rm -Rf boost_1_68_0

  pushd ${BOOST_BASENAME}-source >/dev/null

  BOOST_TOOLSET="clang-5.0"
  BOOST_CFLAGS="-fPIC -std=c++14 -DBOOST_ERROR_CODE_HEADER_ONLY"

  ./bootstrap.sh \
      --with-toolset=clang \
      --prefix=../boost-install \
      --with-libraries=python
  ./b2 clean
  ./b2 toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12 stage release
  ./b2 install toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12

  popd >/dev/null


and ran:
make LibCarla

It fixed itself 💯  :) :) :) 
I am so happy that i could after days :D XD

**Comment by JoveIC** [comment]
@Manojbhat09 I reinstall the whole thing, and now it worked. Thank you!

**Comment by nsubiron** [comment]
Upgrading to Boost 1.68 solves the issue? I'll open an issue to upgrade boost then.

**Comment by versatran01** [comment]
@Manojbhat09 I still have the same problem after installing boost 1.68. Also your comment above is a bit ill-formated. Could you put your working Setup.sh in a gist or a pull request?

**Comment by Manojbhat09** [comment]
Okay I will send that in about an hour

**Comment by JoveIC** [comment]
@versatran01 @nsubiron  I think in my case there was something wrong with my python environment setup. 

During my reinstall, I found out that Python3 wasn't my default python, which causes 'pip install --user setuptools nose2' never correctly installed. So I changed my default python to python3, and used pip3 for the pip install, and it worked.

Hope it helps :)

**Comment by JoveIC** [comment]
@versatran01 Mine too.

And I changed my default to python3, and it worked.

**Comment by versatran01** [comment]
Thanks for the answer, but I doubt python is the problem. I'm using python3 by default already.

**Comment by Manojbhat09** [comment]
If you got this error:
# include <pyconfig.h>
          ^~~~~~~~~~~~
1 error generated.

@sh-shu I did execute

```
sudo update-alternatives --install /usr/bin/clang clang /usr/lib/llvm-5.0/bin/clang 101
sudo apt-get update
sudo apt-get upgrade
python --version
python3 --version
#make sure both are available
make launch
```
And then if there is a cmake3.9 error,
Then follow this: (you can keep the downloaded cmake folder inside carla, but out is also fine)

Currently, the latest version is 3.9.0, the following instructions based on this version. You should therefore check this URL and adjust the file name accordingly.
```
sudo apt-get install build-essential
wget http://www.cmake.org/files/v3.9/cmake-3.9.0.tar.gz
tar xf cmake-3.9.0.tar.gz
cd cmake-3.9.0
./configure
make
```
Now you can have to choose an installation type to decide, I recommend installing with checkinstall, as this creates a DEB package.

With checkinstall
```
sudo apt-get install checkinstall
sudo checkinstall
```
With make install
```
sudo make install
```

Now go back to carla folder and do
```
make launch
```
again 

If that doesnt work, go back to carla/Util/BuildTools and check in setup.sh that everywhere instead of boost_1_67_0 its boost_1_68_0.

Then again make launch, if didt, try again. (try updating and upgrading again, then make again)
You will see there will be a 'Success!' in pink after each step of build
If it comes after libcarla libserver of carlaserver, you are good to go.
UE4 will start automatically

This worked for me :)

**Comment by JoveIC** [comment]
@sh-shu If your error msg is 'cannot find <pyconfig.h>', the second time I ran into this error, instead of install python-dev, I installed python3-dev instead, and it worked :)

**Comment by sh-shu** [comment]
@Manojbhat09 @JoveIC 
Thank you for your kind reply. I figured out that was because of the unsuccessful lib download. For anybody who came across lib problems, please refer to this link: https://github.com/carla-simulator/carla/issues/652
PS. It was based that I have installed python3, cmake 3.12, g++-7, boost 1.58 and make the default link to them.

**Comment by MikeZLin** [comment]
Alternatively, try a manual install of the required version of boost, but following these [instructions](https://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu/24086375#24086375)

**Comment by ziyan0302** [comment]
I have met similar error. What I did is trying to do "make launch" again before doing "make PythonAPI", and this process works for me.
When you do "make launch", you may meet an error: 
cannot stat '/home/ziyan/carla_env/carla/Build/patchelf-install/bin/patchelf': No such file or directory
here is the solution:
https://github.com/carla-simulator/carla/issues/4906

In the "make launch", I saw "BuildLibCarla.sh: Success!" 
Then, I do "make PythonAPI" and finally saw "BuildPythonAPI.sh: Success!"

**Comment by cocobear1223** [comment]
> 

Hello, I'm also National Yang Ming Chiao Tung University student , I have the same problem about  you may meet an error:
cannot stat '/home/ziyan/carla_env/carla/Build/patchelf-install/bin/patchelf': No such file or directory. Could you specify the solution steps? Thanks!!

**Comment by cocobear1223** [comment]
> I have met similar error. What I did is trying to do "make launch" again before doing "make PythonAPI", and this process works for me. When you do "make launch", you may meet an error: cannot stat '/home/ziyan/carla_env/carla/Build/patchelf-install/bin/patchelf': No such file or directory here is the solution: #4906
> 
> In the "make launch", I saw "BuildLibCarla.sh: Success!" Then, I do "make PythonAPI" and finally saw "BuildPythonAPI.sh: Success!"

Hello, I'm also National Yang Ming Chiao Tung University student , I have the same problem about you may meet an error:
cannot stat '/home/ziyan/carla_env/carla/Build/patchelf-install/bin/patchelf': No such file or directory. Could you specify the solution steps? Thanks!!

**Comment by ziyan0302** [comment]
You may have patchelf installed elsewhere so the system can not find it in expected location. Check "whereis patchelf" or directly find patchelf in root folder to see if patcelf is installed.
