### ISSUE TITLE
'Example profile device selector' failed to load

### ISSUE THREAD

**Issue by ghost** [carla-simulator/carla#883]
Hi all,

After a lot of problems with my network I managed to run the setup and rebuild scripts of CARLA in Ubuntu 16.04. When the last mentioned script finished its execution the CARLA project opened in Unreal as expected. 

The thing is I closed Unreal and tried to open the project again to confirm it is all working right. To do so, I navigated into the Binaries/Linux folder of the engine (UnrealEngine_4.18/Engine/Binaries/Linux I believe) and executed ./UE4Editor to open the editor in order to load CARLA project once inside. For my surprise I get the following:

"Plugin 'ExampleProfileDeviceSelector' failed to load because module 'ExampleProfileDeviceSelector' could not be found. Please, ensure that the plugin is properly installed"

![46b31f86-b48d-4674-ab98-57a250136674](https://user-images.githubusercontent.com/14371304/47135003-fc124b80-d2ae-11e8-82fb-95b9af315e12.jpg)

![fe2a1546-7f15-4aee-8915-588545833779](https://user-images.githubusercontent.com/14371304/47135016-06344a00-d2af-11e8-83b9-6f5c0a55df65.jpg)

(Sorry for the poor quality, I know a .txt or copy-paste of the log would have been much better)

Have not tried yet to open the project directly from the terminal, but this is worrying me. I write the issue here because before building CARLA Unreal worked fine. I have googled the problem and have not found a satisfactory answer. Tried to delete Intermediate, Build and Saved files but nothing. 

Has this happened to someone else? Any solution? Should I rebuild Unreal from scratch?

Thanks,

**Comment by nsubiron** [comment]
Uhm, that's something I hadn't tried before, but I can confirm it happens to me as well. I don't see how Carla could break this :thinking:

**Comment by SpakMiguel** [comment]
I have opened the project from terminal with command "./UE4Editor.sh PATH-TO-PROJECT/CarlaUE4.uproject" and it works fine. However, it would be nice if other people could confirm that it is not possible to open UE4Editor directly in Linux after building Carla from source.

**Comment by AdriannaGmz** [comment]
exact same situation happened to me. Solved in the same way by calling the file when running `./UE4Editor "PATH-TO-PROJECT/CarlaUE4.uproject"`

Only problem is that I can not pass any other input argument similar to :
`./CarlaUE4.sh -windowed -ResX=320 -ResY=240 -benchmark -fps=10`

**Comment by AdriannaGmz** [comment]
> exact same situation happened to me. Solved in the same way by calling the file when running `./UE4Editor "PATH-TO-PROJECT/CarlaUE4.uproject"`
> 
> Only problem is that I can not pass any other input argument similar to :
> `./CarlaUE4.sh -windowed -ResX=320 -ResY=240 -benchmark -fps=10`

I better left-clicked the uproject file and opened with UE editor

**Comment by a-jahani** [comment]
You need to give it a path to carla  otherwise change the defaults:

This link might help:
[https://www.epicgames.com/unrealtournament/forums/unreal-tournament-development/ut-development-programming/mac/13460-ut-exampledeviceprofileselector-please-help](https://www.epicgames.com/unrealtournament/forums/unreal-tournament-development/ut-development-programming/mac/13460-ut-exampledeviceprofileselector-please-help)

**Comment by dhruv-g334** [comment]
I still cannot open the unreal engine. The error message still keeps popping up

**Comment by bernatx** [comment]
For those who still has the problem:

1. Open the UE4.sln file inside the source folder with Visual Studio 2019.
2. In the build bar ensure that you have selected '**Development Editor**', 'Win64' and 'UnrealBuildTool' options. Make sure your current selection is '**Development Editor**', as the combo box is too small to see all the text. Better if you choose again.
3. In the solution explorer, right-click UE4 and select Build.

**Comment by LBroKerR** [comment]
Well I have the same issu, i cant open unreal engine from ubuntu 20.04, after i build carla. when i run make launch, it goes down, then can't open unreal edtior.

i got this error: 
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: === Handled ensure: ===
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error:
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: Ensure condition failed: VendorId != EGpuVendorId::Unknown [File:/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanDevice.cpp] [Line: 182]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error:
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: Stack:
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x00007f1fac6b1ea3 libUE4Editor-VulkanRHI.so!FVulkanDevice::FVulkanDevice(FVulkanDynamicRHI*, VkPhysicalDevice_T*) [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanDevice.cpp:182]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x00007f1fac74b8c6 libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::SelectAndInitDevice() [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanRHI.cpp:551]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x00007f1fac747bf3 libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::InitInstance() [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanRHI.cpp:694]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x00007f1fac747808 libUE4Editor-VulkanRHI.so!FVulkanDynamicRHI::Init() [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/VulkanRHI/Private/VulkanRHI.cpp:241]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x00007f208b28818d libUE4Editor-RHI.so!RHIInit(bool) [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/RHI/Private/DynamicRHI.cpp:228]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x0000000000283ba3 UE4Editor!FEngineLoop::PreInitPreStartupScreen(char16_t const*) [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/Launch/Private/LaunchEngineLoop.cpp:2555]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x000000000027aacc UE4Editor!GuardedMain(char16_t const*) [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/Launch/Private/Launch.cpp:127]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x00007f2087d3d286 libUE4Editor-UnixCommonStartup.so!CommonUnixMain(int, char**, int (*)(char16_t const*), void (*)()) [/home/bk2w0w/UnrealEngine_4.26/Engine/Source/Runtime/Unix/UnixCommonStartup/Private/UnixCommonStartup.cpp:264]
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x00007f2087b61083 libc.so.6!__libc_start_main(+0xf2)
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error: [Callstack] 0x0000000000263d39 UE4Editor!_start()
[2023.11.12-22.05.02:146][  0]LogOutputDevice: Error:

at the end when it kill the make i got these:

[2023.11.12-22.10.10:958][  0]LogStaticMesh: Building static mesh SM_SkyscraperNY_02_v03...
/home/bk2w0w/carla/Util/BuildTools/BuildCarlaUE4.sh: line 185: 70525 Killed                  ${GDB} ${UE4_ROOT}/Engine/Binaries/Linux/UE4Editor "${PWD}/CarlaUE4.uproject" ${RHI} ${EDITOR_FLAGS}
make: *** [Util/BuildTools/Linux.mk:7: launch] Error 137


when i run this : ./UE4Editor "PATH-TO-PROJECT/CarlaUE4.uproject" 
its  do the same, but in the end i just got "killed"

**Comment by NBRodrigues** [comment]
Any solution?

**Comment by LBroKerR** [comment]
Well, there is no solution yet, cause I have been doing something else. Well Carla could be run in window. But PC requires minimum an RTX 3060 Ti and gen 11 i9 processor.  And at least  32 gb of ram... not a well optimized simulator at all. Basically Minecraft shall be a better simulator for testing traffic jam solutions....
